### ISSUE TITLE
Error with Flask 3.0.0

### ISSUE THREAD

**Issue by Cabu** [mrevutskyi/flask-restless-ng#42]
```
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/.../venv311/lib/python3.11/site-packages/flask_restless/__init__.py", line 22, in <module>
    from .manager import APIManager  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/.../venv311/lib/python3.11/site-packages/flask_restless/manager.py", line 32, in <module>
    from .views import API
  File "/home/.../venv311/lib/python3.11/site-packages/flask_restless/views/__init__.py", line 23, in <module>
    from .relationships import RelationshipAPI  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/.../venv311/lib/python3.11/site-packages/flask_restless/views/relationships.py", line 19, in <module>
    from flask import escape
ImportError: cannot import name 'escape' from 'flask' (/home/.../venv311/lib/python3.11/site-packages/flask/__init__.py)
python-BaseException
```

**Comment by mrevutskyi** [comment]
Fixed in flask-restless-ng 3.1
